spring:
  application:
    name: redis-stack
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080
  address: 0.0.0.0
logging:
  level:
    root: INFO
    fr.gwen.redis_stack: DEBUG
    org.springframework.data.redis: DEBUG

